-- MySQL Script generated by MySQL Workbench
-- 03/23/18 23:46:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eidSmartClass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eidSmartClass` ;

-- -----------------------------------------------------
-- Schema eidSmartClass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eidSmartClass` DEFAULT CHARACTER SET utf8mb4 ;
USE `eidSmartClass` ;

-- -----------------------------------------------------
-- Table `eidSmartClass`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`Roles` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`Roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `eidSmartClass`.`Roles` (`name` ASC);


-- -----------------------------------------------------
-- Table `eidSmartClass`.`Genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`Genders` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`Genders` (
  `gender_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`gender_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `eidSmartClass`.`Genders` (`name` ASC);


-- -----------------------------------------------------
-- Table `eidSmartClass`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`Users` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`Users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `eIDAS_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender_id` INT NOT NULL DEFAULT 0,
  `role_id` INT NOT NULL DEFAULT 0,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `eidSmartClass`.`Roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Genders1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `eidSmartClass`.`Genders` (`gender_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUsers_UNIQUE` ON `eidSmartClass`.`Users` (`user_id` ASC);

CREATE UNIQUE INDEX `Userscol_UNIQUE` ON `eidSmartClass`.`Users` (`eIDAS_id` ASC);

CREATE INDEX `fk_Users_Roles1_idx` ON `eidSmartClass`.`Users` (`role_id` ASC);

CREATE INDEX `fk_Users_Genders1_idx` ON `eidSmartClass`.`Users` (`gender_id` ASC);


-- -----------------------------------------------------
-- Table `eidSmartClass`.`ClassroomStates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`ClassroomStates` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`ClassroomStates` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `eidSmartClass`.`ClassroomStates` (`name` ASC);


-- -----------------------------------------------------
-- Table `eidSmartClass`.`Classrooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`Classrooms` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`Classrooms` (
  `classroom_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `classroom_status_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`classroom_id`),
  CONSTRAINT `fk_Rooms_RoomStates1`
    FOREIGN KEY (`classroom_status_id`)
    REFERENCES `eidSmartClass`.`ClassroomStates` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Rooms_RoomStates1_idx` ON `eidSmartClass`.`Classrooms` (`classroom_status_id` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `eidSmartClass`.`Classrooms` (`name` ASC);


-- -----------------------------------------------------
-- Table `eidSmartClass`.`ActiveCodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eidSmartClass`.`ActiveCodes` ;

CREATE TABLE IF NOT EXISTS `eidSmartClass`.`ActiveCodes` (
  `active_code_id` BIGINT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `classroom_id` INT NOT NULL,
  `granted_at` DATETIME NOT NULL,
  PRIMARY KEY (`active_code_id`, `user_id`, `classroom_id`),
  CONSTRAINT `fk_ActiveCodes_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `eidSmartClass`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveCodes_Rooms`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `eidSmartClass`.`Classrooms` (`classroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ActiveCodes_Users_idx` ON `eidSmartClass`.`ActiveCodes` (`user_id` ASC);

CREATE INDEX `fk_ActiveCodes_Rooms1_idx` ON `eidSmartClass`.`ActiveCodes` (`classroom_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eidSmartClass`.`Roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `eidSmartClass`;
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'unregistered');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'unidentified');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'visitor');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'virtualparticipant');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'coordinator');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'admin');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'superadmin');
INSERT INTO `eidSmartClass`.`Roles` (`role_id`, `name`) VALUES (DEFAULT, 'blacklisted');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eidSmartClass`.`Genders`
-- -----------------------------------------------------
START TRANSACTION;
USE `eidSmartClass`;
INSERT INTO `eidSmartClass`.`Genders` (`gender_id`, `name`) VALUES (DEFAULT, 'Unspecified');
INSERT INTO `eidSmartClass`.`Genders` (`gender_id`, `name`) VALUES (DEFAULT, 'Male');
INSERT INTO `eidSmartClass`.`Genders` (`gender_id`, `name`) VALUES (DEFAULT, 'Female');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eidSmartClass`.`ClassroomStates`
-- -----------------------------------------------------
START TRANSACTION;
USE `eidSmartClass`;
INSERT INTO `eidSmartClass`.`ClassroomStates` (`status_id`, `name`) VALUES (DEFAULT, 'Inactive');
INSERT INTO `eidSmartClass`.`ClassroomStates` (`status_id`, `name`) VALUES (DEFAULT, 'Active');
INSERT INTO `eidSmartClass`.`ClassroomStates` (`status_id`, `name`) VALUES (DEFAULT, 'Restricted');

COMMIT;

